@extends('rozvrzeni.administrace')
@section('content')

	<!-- banner-bottom -->
	<div class="banner-bottom">
		<!-- container -->
		<div class="container">
			<div class="about-info">
				<h2>Administrace - Kontakt</h2>
			</div>
      
			<div class="faqs-top-grids terms-grids">	
				<table class="table table-bordered table-striped table-hover">
        	<thead>
        		<tr>
        			<th>
        				[HEADER]
        			</th>
        			<th>
        				[HEADER]
        			</th>
        			<th>
        				[HEADER]
        			</th>
        			<th>
        				[HEADER]
        			</th>
        			<th>
        				[HEADER]
        			</th>
        		</tr>
        	</thead>
        	<tbody>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        		<tr>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        			<td>
        				[CONTENT]
        			</td>
        		</tr>
        	</tbody>
        </table>
			</div>
		</div>
		<!-- //container -->
	</div>
	<!-- //banner-bottom -->
  
@endsection